# Generated by Django 5.2.6 on 2026-03-20 15:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_configurationphoto_marklogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активно')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='удалено в')),
                (
                    'name',
                    models.CharField(
                        db_index=True,
                        help_text='Название пакета для сотрудников.',
                        max_length=255,
                        verbose_name='внутреннее название',
                    ),
                ),
                (
                    'public_title',
                    models.CharField(
                        db_index=True,
                        help_text='Заголовок, который видит клиент.',
                        max_length=255,
                        verbose_name='публичный заголовок',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='slug'),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True,
                        help_text='Описание для сотрудников / админки.',
                        verbose_name='внутреннее полное описание',
                    ),
                ),
                (
                    'description_short',
                    models.CharField(
                        blank=True,
                        help_text='Короткое описание для карточки.',
                        max_length=1000,
                        verbose_name='краткое описание',
                    ),
                ),
                (
                    'description_public',
                    models.TextField(
                        blank=True,
                        help_text='Полное описание, которое видит клиент.',
                        verbose_name='публичное HTML-описание',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('DRAFT', 'Черновик'),
                            ('PUBLISHED', 'Опубликован'),
                            ('UNPUBLISHED', 'Снят с публикации'),
                            ('ARCHIVED', 'Архив'),
                        ],
                        db_index=True,
                        default='DRAFT',
                        max_length=20,
                        verbose_name='статус',
                    ),
                ),
                ('is_promo', models.BooleanField(db_index=True, default=False, verbose_name='акция')),
                (
                    'promo_badge',
                    models.CharField(
                        blank=True,
                        help_text='Например: SALE, HIT, АКЦИЯ, -10%.',
                        max_length=100,
                        verbose_name='бейдж акции',
                    ),
                ),
                (
                    'promo_text',
                    models.TextField(blank=True, help_text='Описание акции для клиента.', verbose_name='текст акции'),
                ),
                ('promo_start_at', models.DateTimeField(blank=True, null=True, verbose_name='акция с')),
                ('promo_end_at', models.DateTimeField(blank=True, null=True, verbose_name='акция до')),
                (
                    'package_discount_percent',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        help_text='Общая скидка на пакет целиком.',
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal('0.00')),
                            django.core.validators.MaxValueValidator(Decimal('100.00')),
                        ],
                        verbose_name='общая скидка пакета, %',
                    ),
                ),
                (
                    'modification',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='service_packages',
                        to='cars.modification',
                        verbose_name='автомобиль / модификация',
                    ),
                ),
            ],
            options={
                'verbose_name': 'пакет услуг',
                'verbose_name_plural': 'пакеты услуг',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CarServicePackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активно')),
                ('image', models.ImageField(upload_to='services/packages/', verbose_name='изображение')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='alt текст')),
                (
                    'package',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='image_object',
                        to='catalog.carservicepackage',
                        verbose_name='пакет',
                    ),
                ),
            ],
            options={
                'verbose_name': 'изображение пакета',
                'verbose_name_plural': 'изображения пакетов',
            },
        ),
        migrations.CreateModel(
            name='NomenclatureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активно')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='код')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория номенклатуры',
                'verbose_name_plural': 'категории номенклатуры',
                'ordering': ('name', 'code'),
                'indexes': [models.Index(fields=['is_active', 'name'], name='srv_nomcat_active_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='NomenclatureImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                (
                    'source_type',
                    models.CharField(
                        choices=[
                            ('FILE', 'Файл'),
                            ('ADMIN', 'Вручную через админку'),
                            ('API', 'API'),
                            ('OTHER', 'Другое'),
                        ],
                        db_index=True,
                        default='FILE',
                        max_length=20,
                        verbose_name='тип источника',
                    ),
                ),
                (
                    'source_name',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text='Например: spisok_tovarov.json',
                        max_length=255,
                        verbose_name='имя источника',
                    ),
                ),
                (
                    'source_path',
                    models.CharField(
                        blank=True,
                        help_text='Опционально: путь к файлу, URL или иное описание источника.',
                        max_length=500,
                        verbose_name='путь источника',
                    ),
                ),
                (
                    'file_checksum',
                    models.CharField(blank=True, db_index=True, max_length=128, verbose_name='контрольная сумма файла'),
                ),
                (
                    'raw_payload',
                    models.TextField(
                        blank=True, help_text='Сырой текст импорта, метаданные или сводка.', verbose_name='raw payload'
                    ),
                ),
                ('items_total', models.PositiveIntegerField(default=0, verbose_name='всего записей')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='создано')),
                ('updated_count', models.PositiveIntegerField(default=0, verbose_name='обновлено')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='пропущено')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='ошибок')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'пакет импорта номенклатуры',
                'verbose_name_plural': 'пакеты импорта номенклатуры',
                'ordering': ('-created_at', 'id'),
                'indexes': [
                    models.Index(fields=['source_type', 'created_at'], name='srv_import_src_created_idx'),
                    models.Index(fields=['source_name'], name='srv_import_source_name_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='NomenclatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активно')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='удалено в')),
                ('article', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='артикул')),
                (
                    'item_type',
                    models.CharField(
                        choices=[('PRODUCT', 'Товар'), ('SERVICE', 'Услуга')],
                        db_index=True,
                        max_length=20,
                        verbose_name='тип номенклатуры',
                    ),
                ),
                ('name', models.CharField(db_index=True, max_length=500, verbose_name='название')),
                (
                    'slug',
                    models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='slug'),
                ),
                ('unit', models.CharField(blank=True, default='шт', max_length=50, verbose_name='единица измерения')),
                ('tnved', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ТНВЭД')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='штрихкод')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('description_short', models.CharField(blank=True, max_length=500, verbose_name='краткое описание')),
                ('description_public', models.TextField(blank=True, verbose_name='публичное описание')),
                ('category_level_1_code', models.CharField(blank=True, max_length=64, verbose_name='код категории 1')),
                ('category_level_1_name', models.CharField(blank=True, max_length=255, verbose_name='категория 1')),
                ('category_level_2_code', models.CharField(blank=True, max_length=64, verbose_name='код категории 2')),
                ('category_level_2_name', models.CharField(blank=True, max_length=255, verbose_name='категория 2')),
                ('category_level_3_code', models.CharField(blank=True, max_length=64, verbose_name='код категории 3')),
                ('category_level_3_name', models.CharField(blank=True, max_length=255, verbose_name='категория 3')),
                (
                    'source_type',
                    models.CharField(
                        choices=[
                            ('FILE', 'Файл'),
                            ('ADMIN', 'Вручную через админку'),
                            ('API', 'API'),
                            ('OTHER', 'Другое'),
                        ],
                        db_index=True,
                        default='FILE',
                        max_length=20,
                        verbose_name='тип источника',
                    ),
                ),
                (
                    'source_name',
                    models.CharField(blank=True, db_index=True, max_length=255, verbose_name='имя источника'),
                ),
                (
                    'raw_payload',
                    models.TextField(
                        blank=True,
                        help_text='Сырой текст JSON-объекта или любой иной исходной записи.',
                        verbose_name='raw payload',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='catalog.nomenclaturecategory',
                        verbose_name='категория',
                    ),
                ),
                (
                    'last_import_batch',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='items',
                        to='catalog.nomenclatureimportbatch',
                        verbose_name='последний импорт',
                    ),
                ),
            ],
            options={
                'verbose_name': 'элемент номенклатуры',
                'verbose_name_plural': 'элементы номенклатуры',
                'ordering': ('name', 'article'),
            },
        ),
        migrations.CreateModel(
            name='NomenclatureItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активно')),
                (
                    'image_type',
                    models.CharField(
                        choices=[('IMAGE', 'Изображение'), ('ICON', 'Иконка')],
                        db_index=True,
                        default='IMAGE',
                        max_length=20,
                        verbose_name='тип изображения',
                    ),
                ),
                ('image', models.ImageField(upload_to='services/nomenclature/', verbose_name='файл')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='alt текст')),
                ('is_main', models.BooleanField(db_index=True, default=False, verbose_name='главное изображение')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок сортировки')),
                (
                    'nomenclature_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='images',
                        to='catalog.nomenclatureitem',
                        verbose_name='элемент номенклатуры',
                    ),
                ),
            ],
            options={
                'verbose_name': 'изображение номенклатуры',
                'verbose_name_plural': 'изображения номенклатуры',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='NomenclatureItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активно')),
                (
                    'price_kzt',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='цена, KZT'
                    ),
                ),
                (
                    'source_type',
                    models.CharField(
                        choices=[
                            ('FILE', 'Файл'),
                            ('ADMIN', 'Вручную через админку'),
                            ('API', 'API'),
                            ('OTHER', 'Другое'),
                        ],
                        db_index=True,
                        default='FILE',
                        max_length=20,
                        verbose_name='тип источника',
                    ),
                ),
                (
                    'source_name',
                    models.CharField(blank=True, db_index=True, max_length=255, verbose_name='имя источника'),
                ),
                (
                    'is_imported',
                    models.BooleanField(
                        db_index=True, default=False, verbose_name='импортировано из внешнего источника'
                    ),
                ),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='действует с')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='действует до')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('raw_payload', models.TextField(blank=True, verbose_name='raw payload')),
                (
                    'import_batch',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='price_rows',
                        to='catalog.nomenclatureimportbatch',
                        verbose_name='импорт',
                    ),
                ),
                (
                    'nomenclature_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='prices',
                        to='catalog.nomenclatureitem',
                        verbose_name='элемент номенклатуры',
                    ),
                ),
            ],
            options={
                'verbose_name': 'цена номенклатуры',
                'verbose_name_plural': 'цены номенклатуры',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активно')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='код')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='название')),
                (
                    'slug',
                    models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='slug'),
                ),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок сортировки')),
            ],
            options={
                'verbose_name': 'категория пакета',
                'verbose_name_plural': 'категории пакетов',
                'ordering': ('sort_order', 'name', 'code'),
                'indexes': [
                    models.Index(fields=['is_active', 'sort_order'], name='srv_pkgcat_active_sort_idx'),
                    models.Index(fields=['name'], name='srv_pkgcat_name_idx'),
                ],
            },
        ),
        migrations.AddField(
            model_name='carservicepackage',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='packages',
                to='catalog.packagecategory',
                verbose_name='категория пакета',
            ),
        ),
        migrations.CreateModel(
            name='PackageItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активно')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='удалено в')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок сортировки')),
                (
                    'package',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='item_categories',
                        to='catalog.carservicepackage',
                        verbose_name='пакет',
                    ),
                ),
            ],
            options={
                'verbose_name': 'категория элементов пакета',
                'verbose_name_plural': 'категории элементов пакета',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активно')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='удалено в')),
                (
                    'quantity',
                    models.PositiveIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество'
                    ),
                ),
                (
                    'discount_percent',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal('0.00')),
                            django.core.validators.MaxValueValidator(Decimal('100.00')),
                        ],
                        verbose_name='скидка, %',
                    ),
                ),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок сортировки')),
                (
                    'item_type_snapshot',
                    models.CharField(
                        blank=True,
                        choices=[('PRODUCT', 'Товар'), ('SERVICE', 'Услуга')],
                        max_length=20,
                        verbose_name='тип элемента (snapshot)',
                    ),
                ),
                ('article_snapshot', models.CharField(blank=True, max_length=128, verbose_name='артикул (snapshot)')),
                ('name_snapshot', models.CharField(blank=True, max_length=500, verbose_name='название (snapshot)')),
                (
                    'unit_snapshot',
                    models.CharField(blank=True, max_length=50, verbose_name='единица измерения (snapshot)'),
                ),
                (
                    'base_price_snapshot',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=12,
                        verbose_name='базовая цена, KZT (snapshot)',
                    ),
                ),
                (
                    'nomenclature_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='package_items',
                        to='catalog.nomenclatureitem',
                        verbose_name='элемент номенклатуры',
                    ),
                ),
                (
                    'package',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='catalog.carservicepackage',
                        verbose_name='пакет',
                    ),
                ),
                (
                    'package_category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='catalog.packageitemcategory',
                        verbose_name='категория элементов пакета',
                    ),
                ),
            ],
            options={
                'verbose_name': 'элемент пакета',
                'verbose_name_plural': 'элементы пакета',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='nomenclatureitem',
            index=models.Index(fields=['item_type'], name='srv_nomitem_type_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclatureitem',
            index=models.Index(fields=['category'], name='srv_nomitem_category_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclatureitem',
            index=models.Index(fields=['is_active', 'item_type'], name='srv_nomitem_active_type_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclatureitem',
            index=models.Index(fields=['is_deleted'], name='srv_nomitem_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclatureitem',
            index=models.Index(fields=['name'], name='srv_nomitem_name_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclatureitemimage',
            index=models.Index(fields=['nomenclature_item', 'is_main'], name='srv_nomimg_item_main_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclatureitemimage',
            index=models.Index(fields=['image_type', 'is_active'], name='srv_nomimg_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclatureitemprice',
            index=models.Index(fields=['nomenclature_item', 'is_active'], name='srv_nomprice_item_active_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclatureitemprice',
            index=models.Index(fields=['source_type', 'created_at'], name='srv_nomprice_src_created_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclatureitemprice',
            index=models.Index(fields=['starts_at', 'ends_at'], name='srv_nomprice_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='carservicepackage',
            index=models.Index(fields=['modification'], name='srv_package_modification_idx'),
        ),
        migrations.AddIndex(
            model_name='carservicepackage',
            index=models.Index(fields=['category'], name='srv_package_category_idx'),
        ),
        migrations.AddIndex(
            model_name='carservicepackage',
            index=models.Index(fields=['status'], name='srv_package_status_idx'),
        ),
        migrations.AddIndex(
            model_name='carservicepackage',
            index=models.Index(fields=['is_promo'], name='srv_package_promo_idx'),
        ),
        migrations.AddIndex(
            model_name='carservicepackage',
            index=models.Index(fields=['is_deleted'], name='srv_package_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='carservicepackage',
            index=models.Index(fields=['created_at'], name='srv_package_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='carservicepackage',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_deleted', False)),
                fields=('modification', 'category'),
                name='srv_package_mod_category_not_deleted_uniq',
            ),
        ),
        migrations.AddIndex(
            model_name='packageitemcategory',
            index=models.Index(fields=['package', 'sort_order'], name='cat_pic_pkg_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='packageitemcategory',
            index=models.Index(fields=['is_deleted'], name='cat_pic_del_idx'),
        ),
        migrations.AddConstraint(
            model_name='packageitemcategory',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_deleted', False)), fields=('package', 'name'), name='srv_pkgcat_pkg_name_uniq'
            ),
        ),
        migrations.AddIndex(
            model_name='packageitem',
            index=models.Index(fields=['package', 'sort_order'], name='srv_pkgitem_package_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='packageitem',
            index=models.Index(fields=['package_category'], name='srv_pkgitem_category_idx'),
        ),
        migrations.AddIndex(
            model_name='packageitem',
            index=models.Index(fields=['nomenclature_item'], name='srv_pkgitem_nomenclature_idx'),
        ),
        migrations.AddIndex(
            model_name='packageitem',
            index=models.Index(fields=['is_deleted'], name='srv_pkgitem_deleted_idx'),
        ),
        migrations.AddConstraint(
            model_name='packageitem',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_deleted', False)),
                fields=('package', 'nomenclature_item'),
                name='srv_pkgitem_package_nomenclature_not_deleted_uniq',
            ),
        ),
    ]
