# Generated by Django 5.2.6 on 2026-03-19 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('source_id', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='source id')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='название')),
                ('name_ru', models.CharField(blank=True, max_length=255, verbose_name='название (RU)')),
                ('year_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='год начала')),
                ('year_to', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='год окончания')),
                (
                    'class_code',
                    models.CharField(
                        choices=[
                            ('A', 'A'),
                            ('B', 'B'),
                            ('C', 'C'),
                            ('D', 'D'),
                            ('E', 'E'),
                            ('F', 'F'),
                            ('J', 'J'),
                            ('M', 'M'),
                            ('S', 'S'),
                            ('UNKNOWN', 'Неизвестно'),
                        ],
                        db_index=True,
                        default='UNKNOWN',
                        max_length=16,
                        verbose_name='класс модели',
                    ),
                ),
                ('class_code_raw', models.CharField(blank=True, max_length=10, verbose_name='класс модели (raw)')),
            ],
            options={
                'verbose_name': 'модель автомобиля',
                'verbose_name_plural': 'модели автомобилей',
                'ordering': ('mark__name', 'name', 'source_id'),
            },
        ),
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='код')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'тип кузова',
                'verbose_name_plural': 'типы кузова',
                'ordering': ('name', 'code'),
                'indexes': [models.Index(fields=['name'], name='cars_bodytype_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('source_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='source id')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='название')),
                ('year_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='год начала')),
                ('year_to', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='год окончания')),
                (
                    'model',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='generations',
                        to='cars.carmodel',
                        verbose_name='модель',
                    ),
                ),
            ],
            options={
                'verbose_name': 'поколение',
                'verbose_name_plural': 'поколения',
                'ordering': ('model__mark__name', 'model__name', 'year_from', 'name', 'source_id'),
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('source_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='source id')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='название')),
                (
                    'doors_count',
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='количество дверей'),
                ),
                (
                    'body_type',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='configurations',
                        to='cars.bodytype',
                        verbose_name='тип кузова',
                    ),
                ),
                (
                    'generation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='configurations',
                        to='cars.generation',
                        verbose_name='поколение',
                    ),
                ),
            ],
            options={
                'verbose_name': 'конфигурация',
                'verbose_name_plural': 'конфигурации',
                'ordering': ('generation__model__mark__name', 'generation__model__name', 'name', 'source_id'),
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('source_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='source id')),
                (
                    'source_numeric_id',
                    models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='source numeric id'),
                ),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='название')),
                ('name_ru', models.CharField(blank=True, max_length=255, verbose_name='название (RU)')),
                ('year_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='год начала')),
                ('year_to', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='год окончания')),
                ('is_popular', models.BooleanField(default=False, verbose_name='популярная')),
                (
                    'country',
                    models.CharField(
                        choices=[
                            ('AUSTRALIA', 'Австралия'),
                            ('AUSTRIA', 'Австрия'),
                            ('BELARUS', 'Беларусь'),
                            ('BRAZIL', 'Бразилия'),
                            ('UNITED_KINGDOM', 'Великобритания'),
                            ('VIETNAM', 'Вьетнам'),
                            ('GERMANY', 'Германия'),
                            ('DENMARK', 'Дания'),
                            ('ISRAEL', 'Израиль'),
                            ('INDIA', 'Индия'),
                            ('IRAN', 'Иран'),
                            ('SPAIN', 'Испания'),
                            ('ITALY', 'Италия'),
                            ('CHINA', 'Китай'),
                            ('LATVIA', 'Латвия'),
                            ('MALAYSIA', 'Малайзия'),
                            ('MEXICO', 'Мексика'),
                            ('NETHERLANDS', 'Нидерланды'),
                            ('NORWAY', 'Норвегия'),
                            ('UAE', 'Объединённые Арабские Эмираты'),
                            ('PAKISTAN', 'Пакистан'),
                            ('POLAND', 'Польша'),
                            ('RUSSIA', 'Россия'),
                            ('ROMANIA', 'Румыния'),
                            ('SERBIA', 'Сербия'),
                            ('USA', 'США'),
                            ('THAILAND', 'Таиланд'),
                            ('TAIWAN', 'Тайвань'),
                            ('TURKEY', 'Турция'),
                            ('UZBEKISTAN', 'Узбекистан'),
                            ('UKRAINE', 'Украина'),
                            ('FRANCE', 'Франция'),
                            ('CROATIA', 'Хорватия'),
                            ('CZECHIA', 'Чехия'),
                            ('SWITZERLAND', 'Швейцария'),
                            ('SWEDEN', 'Швеция'),
                            ('SOUTH_KOREA', 'Южная Корея'),
                            ('JAPAN', 'Япония'),
                            ('UNKNOWN', 'Неизвестно'),
                        ],
                        db_index=True,
                        default='UNKNOWN',
                        max_length=64,
                        verbose_name='страна',
                    ),
                ),
                ('country_raw', models.CharField(blank=True, max_length=100, verbose_name='страна (raw)')),
            ],
            options={
                'verbose_name': 'марка',
                'verbose_name_plural': 'марки',
                'ordering': ('name', 'source_id'),
                'indexes': [
                    models.Index(fields=['is_popular'], name='cars_mark_popular_idx'),
                    models.Index(fields=['year_from', 'year_to'], name='cars_mark_years_idx'),
                ],
            },
        ),
        migrations.AddField(
            model_name='carmodel',
            name='mark',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='car_models',
                to='cars.mark',
                verbose_name='марка',
            ),
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('source_id', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='source id')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='название')),
                (
                    'group_name',
                    models.CharField(blank=True, db_index=True, max_length=255, verbose_name='группа / комплектация'),
                ),
                ('is_closed', models.BooleanField(blank=True, null=True, verbose_name='закрыта')),
                ('price_from', models.BigIntegerField(blank=True, null=True, verbose_name='цена от')),
                ('price_to', models.BigIntegerField(blank=True, null=True, verbose_name='цена до')),
                (
                    'configuration',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='modifications',
                        to='cars.configuration',
                        verbose_name='конфигурация',
                    ),
                ),
            ],
            options={
                'verbose_name': 'модификация',
                'verbose_name_plural': 'модификации',
                'ordering': (
                    'configuration__generation__model__mark__name',
                    'configuration__generation__model__name',
                    'configuration__name',
                    'name',
                    'source_id',
                ),
            },
        ),
        migrations.CreateModel(
            name='ModificationRawSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='raw payload')),
                ('unparsed_payload', models.JSONField(blank=True, default=dict, verbose_name='unparsed payload')),
                ('parse_notes', models.TextField(blank=True, verbose_name='заметки парсинга')),
                (
                    'modification',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='raw_specification',
                        to='cars.modification',
                        verbose_name='модификация',
                    ),
                ),
            ],
            options={
                'verbose_name': 'сырые характеристики модификации',
                'verbose_name_plural': 'сырые характеристики модификаций',
            },
        ),
        migrations.CreateModel(
            name='ModificationSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                (
                    'auto_class',
                    models.CharField(
                        choices=[
                            ('A', 'A'),
                            ('B', 'B'),
                            ('C', 'C'),
                            ('D', 'D'),
                            ('E', 'E'),
                            ('F', 'F'),
                            ('J', 'J'),
                            ('M', 'M'),
                            ('S', 'S'),
                            ('UNKNOWN', 'Неизвестно'),
                        ],
                        db_index=True,
                        default='UNKNOWN',
                        max_length=16,
                        verbose_name='класс авто',
                    ),
                ),
                ('auto_class_raw', models.CharField(blank=True, max_length=10, verbose_name='класс авто (raw)')),
                (
                    'steering_wheel_position',
                    models.CharField(
                        choices=[
                            ('LEFT', 'Левый'),
                            ('RIGHT', 'Правый'),
                            ('LEFT_RIGHT', 'Левый/Правый'),
                            ('RIGHT_LEFT', 'Правый/Левый'),
                            ('UNKNOWN', 'Неизвестно'),
                        ],
                        db_index=True,
                        default='UNKNOWN',
                        max_length=20,
                        verbose_name='положение руля',
                    ),
                ),
                (
                    'steering_wheel_position_raw',
                    models.CharField(blank=True, max_length=50, verbose_name='положение руля (raw)'),
                ),
                ('body_size_raw', models.CharField(blank=True, max_length=255, verbose_name='размер кузова (raw)')),
                ('length_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='длина, мм')),
                ('width_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='ширина, мм')),
                ('height_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='высота, мм')),
                ('wheelbase_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='колёсная база, мм')),
                ('ground_clearance_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='клиренс, мм')),
                (
                    'front_track_mm',
                    models.PositiveIntegerField(blank=True, null=True, verbose_name='передняя колея, мм'),
                ),
                ('rear_track_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='задняя колея, мм')),
                (
                    'doors_count',
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='количество дверей'),
                ),
                (
                    'seats_count',
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='количество мест'),
                ),
                ('origin_tires_size_raw', models.TextField(blank=True, verbose_name='размер штатных шин (raw)')),
                ('landing_wheels_size_raw', models.TextField(blank=True, verbose_name='посадочный размер колёс (raw)')),
                ('disk_size_raw', models.TextField(blank=True, verbose_name='размер дисков (raw)')),
                ('wheel_size_raw', models.TextField(blank=True, verbose_name='wheel size (raw)')),
                ('boot_volume_raw', models.CharField(blank=True, max_length=255, verbose_name='объём багажника (raw)')),
                (
                    'trunk_volume_min_l',
                    models.PositiveIntegerField(blank=True, null=True, verbose_name='объём багажника min, л'),
                ),
                (
                    'trunk_volume_max_l',
                    models.PositiveIntegerField(blank=True, null=True, verbose_name='объём багажника max, л'),
                ),
                (
                    'fuel_tank_volume_l',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='объём бака, л'
                    ),
                ),
                ('curb_weight_kg', models.PositiveIntegerField(blank=True, null=True, verbose_name='масса, кг')),
                (
                    'gross_weight_kg',
                    models.PositiveIntegerField(blank=True, null=True, verbose_name='полная масса, кг'),
                ),
                (
                    'transmission_type',
                    models.CharField(
                        choices=[
                            ('AUTOMATIC', 'Автомат'),
                            ('VARIATOR', 'Вариатор'),
                            ('MANUAL', 'Механика'),
                            ('ROBOT', 'Робот'),
                            ('UNKNOWN', 'Неизвестно'),
                        ],
                        db_index=True,
                        default='UNKNOWN',
                        max_length=20,
                        verbose_name='тип трансмиссии',
                    ),
                ),
                (
                    'transmission_type_raw',
                    models.CharField(blank=True, max_length=50, verbose_name='тип трансмиссии (raw)'),
                ),
                (
                    'gears_count',
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='количество передач'),
                ),
                (
                    'drive_type',
                    models.CharField(
                        choices=[
                            ('REAR', 'Задний'),
                            ('FRONT', 'Передний'),
                            ('ALL_WHEEL', 'Полный'),
                            ('UNKNOWN', 'Неизвестно'),
                        ],
                        db_index=True,
                        default='UNKNOWN',
                        max_length=20,
                        verbose_name='тип привода',
                    ),
                ),
                ('drive_type_raw', models.CharField(blank=True, max_length=50, verbose_name='тип привода (raw)')),
                (
                    'transmission_code',
                    models.CharField(
                        choices=[
                            ('AUTOMATIC', 'AUTOMATIC'),
                            ('MECHANICAL', 'MECHANICAL'),
                            ('ROBOT', 'ROBOT'),
                            ('VARIATOR', 'VARIATOR'),
                            ('UNKNOWN', 'UNKNOWN'),
                        ],
                        db_index=True,
                        default='UNKNOWN',
                        max_length=20,
                        verbose_name='код трансмиссии',
                    ),
                ),
                (
                    'transmission_code_raw',
                    models.CharField(blank=True, max_length=50, verbose_name='код трансмиссии (raw)'),
                ),
                (
                    'front_suspension_type',
                    models.CharField(
                        choices=[
                            ('DEPENDENT_SPRING', 'Зависимая, пружинная'),
                            ('DEPENDENT_LEAF', 'Зависимая, рессорная'),
                            ('DEPENDENT_PNEUMATIC', 'Зависимая, пневмоэлемент'),
                            ('INDEPENDENT_HYDROPNEUMATIC', 'Независимая, гидропневмоэлемент'),
                            ('INDEPENDENT_PNEUMATIC', 'Независимая, пневмоэлемент'),
                            ('INDEPENDENT_SPRING', 'Независимая, пружинная'),
                            ('INDEPENDENT_LEAF', 'Независимая, рессорная'),
                            ('INDEPENDENT_TORSION', 'Независимая, торсионная'),
                            ('SEMI_INDEPENDENT_SPRING', 'Полунезависимая, пружинная'),
                            ('SEMI_INDEPENDENT_TORSION', 'Полунезависимая, торсионная'),
                            ('UNKNOWN', 'Неизвестно'),
                        ],
                        default='UNKNOWN',
                        max_length=40,
                        verbose_name='передняя подвеска',
                    ),
                ),
                (
                    'front_suspension_type_raw',
                    models.CharField(blank=True, max_length=255, verbose_name='передняя подвеска (raw)'),
                ),
                (
                    'rear_suspension_type',
                    models.CharField(
                        choices=[
                            ('DEPENDENT_SPRING', 'Зависимая, пружинная'),
                            ('DEPENDENT_LEAF', 'Зависимая, рессорная'),
                            ('DEPENDENT_PNEUMATIC', 'Зависимая, пневмоэлемент'),
                            ('INDEPENDENT_HYDROPNEUMATIC', 'Независимая, гидропневмоэлемент'),
                            ('INDEPENDENT_PNEUMATIC', 'Независимая, пневмоэлемент'),
                            ('INDEPENDENT_SPRING', 'Независимая, пружинная'),
                            ('INDEPENDENT_LEAF', 'Независимая, рессорная'),
                            ('INDEPENDENT_TORSION', 'Независимая, торсионная'),
                            ('SEMI_INDEPENDENT_SPRING', 'Полунезависимая, пружинная'),
                            ('SEMI_INDEPENDENT_TORSION', 'Полунезависимая, торсионная'),
                            ('UNKNOWN', 'Неизвестно'),
                        ],
                        default='UNKNOWN',
                        max_length=40,
                        verbose_name='задняя подвеска',
                    ),
                ),
                (
                    'rear_suspension_type_raw',
                    models.CharField(blank=True, max_length=255, verbose_name='задняя подвеска (raw)'),
                ),
                (
                    'front_brake_type',
                    models.CharField(
                        choices=[
                            ('DRUM', 'Барабанные'),
                            ('DISC', 'Дисковые'),
                            ('VENTILATED_DISC', 'Дисковые вентилируемые'),
                            ('CERAMIC', 'Керамические'),
                            ('VENTILATED_CERAMIC', 'Керамические вентилируемые'),
                            ('UNKNOWN', 'Неизвестно'),
                        ],
                        default='UNKNOWN',
                        max_length=30,
                        verbose_name='передние тормоза',
                    ),
                ),
                (
                    'front_brake_type_raw',
                    models.CharField(blank=True, max_length=255, verbose_name='передние тормоза (raw)'),
                ),
                (
                    'rear_brake_type',
                    models.CharField(
                        choices=[
                            ('DRUM', 'Барабанные'),
                            ('DISC', 'Дисковые'),
                            ('VENTILATED_DISC', 'Дисковые вентилируемые'),
                            ('CERAMIC', 'Керамические'),
                            ('VENTILATED_CERAMIC', 'Керамические вентилируемые'),
                            ('UNKNOWN', 'Неизвестно'),
                        ],
                        default='UNKNOWN',
                        max_length=30,
                        verbose_name='задние тормоза',
                    ),
                ),
                (
                    'rear_brake_type_raw',
                    models.CharField(blank=True, max_length=255, verbose_name='задние тормоза (raw)'),
                ),
                (
                    'max_speed_kmh',
                    models.PositiveIntegerField(blank=True, null=True, verbose_name='максимальная скорость, км/ч'),
                ),
                (
                    'acceleration_0_to_100_sec',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='разгон 0-100, сек'
                    ),
                ),
                ('consumption_raw', models.CharField(blank=True, max_length=255, verbose_name='расход (raw)')),
                (
                    'consumption_city_l_100km',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='расход в городе, л/100км'
                    ),
                ),
                (
                    'consumption_highway_l_100km',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='расход на трассе, л/100км'
                    ),
                ),
                (
                    'consumption_mixed_l_100km',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='смешанный расход, л/100км'
                    ),
                ),
                (
                    'electric_consumption_kwh_100km',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name='расход электроэнергии, кВт⋅ч/100км',
                    ),
                ),
                (
                    'co2_emission_g_km',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='выбросы CO₂, г/км'
                    ),
                ),
                (
                    'fuel_type',
                    models.CharField(
                        choices=[
                            ('AI_76', 'АИ-76'),
                            ('AI_80', 'АИ-80'),
                            ('AI_92', 'АИ-92'),
                            ('AI_95', 'АИ-95'),
                            ('AI_98', 'АИ-98'),
                            ('HYDROGEN', 'Водород'),
                            ('GASOLINE_GAS', 'Газ (бензин)'),
                            ('DIESEL', 'ДТ'),
                            ('UNKNOWN', 'Неизвестно'),
                        ],
                        db_index=True,
                        default='UNKNOWN',
                        max_length=20,
                        verbose_name='тип топлива',
                    ),
                ),
                ('fuel_type_raw', models.CharField(blank=True, max_length=100, verbose_name='тип топлива (raw)')),
                (
                    'emission_standard',
                    models.CharField(
                        choices=[
                            ('EURO_1', 'Euro 1'),
                            ('EURO_2', 'Euro 2'),
                            ('EURO_3', 'Euro 3'),
                            ('EURO_4', 'Euro 4'),
                            ('EURO_5', 'Euro 5'),
                            ('EURO_6', 'Euro 6'),
                            ('UNKNOWN', 'Неизвестно'),
                        ],
                        default='UNKNOWN',
                        max_length=20,
                        verbose_name='экологический стандарт',
                    ),
                ),
                (
                    'emission_standard_raw',
                    models.CharField(blank=True, max_length=50, verbose_name='экологический стандарт (raw)'),
                ),
                (
                    'consumption_calc_type',
                    models.CharField(
                        choices=[
                            ('CLTC', 'CLTC'),
                            ('EPA', 'EPA'),
                            ('NEDC', 'NEDC'),
                            ('WLTP', 'WLTP'),
                            ('UNKNOWN', 'Неизвестно'),
                        ],
                        default='UNKNOWN',
                        max_length=20,
                        verbose_name='методика расчёта расхода',
                    ),
                ),
                (
                    'consumption_calc_type_raw',
                    models.CharField(blank=True, max_length=50, verbose_name='методика расчёта расхода (raw)'),
                ),
                (
                    'powertrain_type',
                    models.CharField(
                        choices=[
                            ('PETROL', 'Бензиновый'),
                            ('HYDROGEN', 'Водородный'),
                            ('LPG', 'ГБО'),
                            ('HYBRID', 'Гибридный'),
                            ('DIESEL', 'Дизельный'),
                            ('ELECTRIC', 'Электро'),
                            ('UNKNOWN', 'Неизвестно'),
                        ],
                        db_index=True,
                        default='UNKNOWN',
                        max_length=20,
                        verbose_name='тип силовой установки',
                    ),
                ),
                (
                    'powertrain_type_raw',
                    models.CharField(blank=True, max_length=100, verbose_name='тип силовой установки (raw)'),
                ),
                (
                    'engine_position_layout',
                    models.CharField(blank=True, max_length=100, verbose_name='расположение двигателя'),
                ),
                (
                    'displacement_cc',
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name='объём двигателя, см³'
                    ),
                ),
                (
                    'aspiration_type',
                    models.CharField(
                        choices=[
                            ('COMPRESSOR', 'Компрессор'),
                            ('NONE', 'нет'),
                            ('TURBO', 'Турбонаддув'),
                            ('UNKNOWN', 'Неизвестно'),
                        ],
                        default='UNKNOWN',
                        max_length=20,
                        verbose_name='тип наддува',
                    ),
                ),
                ('aspiration_type_raw', models.CharField(blank=True, max_length=100, verbose_name='тип наддува (raw)')),
                ('max_power_raw', models.CharField(blank=True, max_length=255, verbose_name='мощность (raw)')),
                (
                    'horse_power_hp',
                    models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='мощность, л.с.'),
                ),
                (
                    'power_kw',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='мощность, кВт'
                    ),
                ),
                ('power_rpm_raw', models.CharField(blank=True, max_length=100, verbose_name='обороты мощности (raw)')),
                ('torque_raw', models.CharField(blank=True, max_length=255, verbose_name='крутящий момент (raw)')),
                ('torque_nm', models.PositiveIntegerField(blank=True, null=True, verbose_name='крутящий момент, Н⋅м')),
                ('torque_rpm_raw', models.CharField(blank=True, max_length=100, verbose_name='обороты момента (raw)')),
                (
                    'cylinders_layout',
                    models.CharField(
                        choices=[
                            ('V', 'V-образное'),
                            ('VR', 'V-образное с малым углом'),
                            ('W', 'W-образное'),
                            ('BOXER', 'Оппозитное'),
                            ('ROTARY', 'Ротор'),
                            ('INLINE', 'Рядное'),
                            ('UNKNOWN', 'Неизвестно'),
                        ],
                        default='UNKNOWN',
                        max_length=20,
                        verbose_name='расположение цилиндров',
                    ),
                ),
                (
                    'cylinders_layout_raw',
                    models.CharField(blank=True, max_length=100, verbose_name='расположение цилиндров (raw)'),
                ),
                (
                    'cylinders_count',
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='количество цилиндров'),
                ),
                (
                    'valves_count',
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='количество клапанов'),
                ),
                (
                    'fuel_injection_type',
                    models.CharField(
                        choices=[
                            ('COMMON_RAIL', 'Common rail (дизель)'),
                            ('CARBURETOR', 'Карбюратор'),
                            ('COMBINED_INJECTION', 'Комбинированный впрыск (непосредственно-распределенный)'),
                            ('UNIT_INJECTOR', 'Насос-форсунка (дизель)'),
                            ('DIRECT_INJECTION', 'Непосредственный впрыск (прямой)'),
                            ('MULTIPOINT_INJECTION', 'Распределенный впрыск (многоточечный)'),
                            ('DIESEL_PUMP', 'ТНВД (дизель)'),
                            ('SINGLE_POINT_INJECTION', 'Центральный впрыск (моновпрыск или одноточечный)'),
                            ('UNKNOWN', 'Неизвестно'),
                        ],
                        default='UNKNOWN',
                        max_length=30,
                        verbose_name='тип впрыска',
                    ),
                ),
                (
                    'fuel_injection_type_raw',
                    models.CharField(blank=True, max_length=255, verbose_name='тип впрыска (raw)'),
                ),
                (
                    'compression_ratio',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='степень сжатия'
                    ),
                ),
                ('diameter_raw', models.CharField(blank=True, max_length=100, verbose_name='diameter (raw)')),
                (
                    'cylinder_bore_mm',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='диаметр цилиндра, мм'
                    ),
                ),
                (
                    'piston_stroke_mm',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ход поршня, мм'
                    ),
                ),
                (
                    'engine_code',
                    models.CharField(blank=True, db_index=True, max_length=255, verbose_name='код двигателя'),
                ),
                ('engine_code_secondary', models.CharField(blank=True, max_length=255, verbose_name='код двигателя 2')),
                (
                    'valvetrain_type',
                    models.CharField(
                        choices=[
                            ('DOHC', 'DOHC'),
                            ('OHC', 'OHC'),
                            ('OHV', 'OHV'),
                            ('SOHC', 'SOHC'),
                            ('SV', 'SV'),
                            ('UNKNOWN', 'Неизвестно'),
                        ],
                        default='UNKNOWN',
                        max_length=20,
                        verbose_name='тип ГРМ',
                    ),
                ),
                ('valvetrain_type_raw', models.CharField(blank=True, max_length=50, verbose_name='тип ГРМ (raw)')),
                (
                    'battery_capacity_kwh',
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name='ёмкость батареи, кВт⋅ч',
                    ),
                ),
                (
                    'battery_capacity_usable_kwh',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name='полезная ёмкость батареи, кВт⋅ч',
                    ),
                ),
                (
                    'battery_type',
                    models.CharField(
                        choices=[
                            ('HFC', 'Водородные элементы (HFC)'),
                            ('LFP', 'Литий-железо-фосфатная (LFP)'),
                            ('LI_ION', 'Литий-ионная (Li-ion)'),
                            ('LI_NMC', 'Литий-никель-марганец-кобальт-оксидная (Li-NMC)'),
                            ('LI_POL', 'Литий-полимерная (Li-pol)'),
                            ('NA_ION', 'Натрий-ионная (Na-ion)'),
                            ('NIH2', 'Никель-водородная (NiH2)'),
                            ('NICD', 'Никель-кадмиевая (NiCd)'),
                            ('NIMH', 'Никель-металлогидридная (NiMH)'),
                            ('LEAD_ACID', 'Свинцово-кислотная (Lead-acid)'),
                            ('UNKNOWN', 'Неизвестно'),
                        ],
                        default='UNKNOWN',
                        max_length=20,
                        verbose_name='тип батареи',
                    ),
                ),
                ('battery_type_raw', models.CharField(blank=True, max_length=255, verbose_name='тип батареи (raw)')),
                (
                    'electric_range_km',
                    models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='запас хода, км'),
                ),
                (
                    'ac_charge_time_raw',
                    models.CharField(blank=True, max_length=255, verbose_name='время AC-зарядки (raw)'),
                ),
                (
                    'dc_fast_charge_time_raw',
                    models.CharField(blank=True, max_length=255, verbose_name='время быстрой DC-зарядки (raw)'),
                ),
                ('quickcharge_description', models.TextField(blank=True, verbose_name='описание быстрой зарядки')),
                ('charging_port_types_raw', models.TextField(blank=True, verbose_name='типы зарядных портов (raw)')),
                (
                    'max_charge_power_kw',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name='максимальная мощность зарядки, кВт',
                    ),
                ),
                (
                    'battery_charge_cycles',
                    models.PositiveIntegerField(blank=True, null=True, verbose_name='циклы заряда'),
                ),
                (
                    'battery_temp_raw',
                    models.CharField(blank=True, max_length=100, verbose_name='температура батареи (raw)'),
                ),
                (
                    'modification',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='specification',
                        to='cars.modification',
                        verbose_name='модификация',
                    ),
                ),
            ],
            options={
                'verbose_name': 'характеристики модификации',
                'verbose_name_plural': 'характеристики модификаций',
            },
        ),
        migrations.CreateModel(
            name='OptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='код')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='название')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок сортировки')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
            ],
            options={
                'verbose_name': 'категория опций',
                'verbose_name_plural': 'категории опций',
                'ordering': ('sort_order', 'name', 'code'),
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='cars_optcat_active_sort_idx')],
            },
        ),
        migrations.CreateModel(
            name='OptionDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('code', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='код')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='название')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='полное название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                (
                    'category',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='options',
                        to='cars.optioncategory',
                        verbose_name='категория',
                    ),
                ),
            ],
            options={
                'verbose_name': 'опция',
                'verbose_name_plural': 'опции',
                'ordering': ('sort_order', 'name', 'code'),
            },
        ),
        migrations.CreateModel(
            name='ModificationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('value_bool', models.BooleanField(blank=True, null=True, verbose_name='значение')),
                ('raw_value', models.CharField(blank=True, max_length=255, verbose_name='raw value')),
                ('source_column', models.CharField(blank=True, max_length=128, verbose_name='source column')),
                (
                    'modification',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='option_values',
                        to='cars.modification',
                        verbose_name='модификация',
                    ),
                ),
                (
                    'option_definition',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='modification_values',
                        to='cars.optiondefinition',
                        verbose_name='опция',
                    ),
                ),
            ],
            options={
                'verbose_name': 'значение опции модификации',
                'verbose_name_plural': 'значения опций модификации',
            },
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['model', 'year_from', 'year_to'], name='cars_gen_model_yrs_idx'),
        ),
        migrations.AddIndex(
            model_name='configuration',
            index=models.Index(fields=['generation', 'name'], name='cars_cfg_gen_name_idx'),
        ),
        migrations.AddIndex(
            model_name='configuration',
            index=models.Index(fields=['body_type'], name='cars_config_bodytype_idx'),
        ),
        migrations.AddIndex(
            model_name='carmodel',
            index=models.Index(fields=['mark', 'name'], name='cars_carmodel_mark_name_idx'),
        ),
        migrations.AddIndex(
            model_name='carmodel',
            index=models.Index(fields=['year_from', 'year_to'], name='cars_carmodel_years_idx'),
        ),
        migrations.AddIndex(
            model_name='modification',
            index=models.Index(fields=['configuration', 'name'], name='cars_modif_config_name_idx'),
        ),
        migrations.AddIndex(
            model_name='modification',
            index=models.Index(fields=['group_name'], name='cars_modif_group_name_idx'),
        ),
        migrations.AddIndex(
            model_name='modification',
            index=models.Index(fields=['is_closed'], name='cars_modif_closed_idx'),
        ),
        migrations.AddIndex(
            model_name='modification',
            index=models.Index(fields=['price_from', 'price_to'], name='cars_modif_prices_idx'),
        ),
        migrations.AddIndex(
            model_name='modificationspecification',
            index=models.Index(fields=['auto_class'], name='cars_spec_auto_class_idx'),
        ),
        migrations.AddIndex(
            model_name='modificationspecification',
            index=models.Index(fields=['steering_wheel_position'], name='cars_spec_steering_idx'),
        ),
        migrations.AddIndex(
            model_name='modificationspecification',
            index=models.Index(fields=['transmission_type'], name='cars_spec_transmission_idx'),
        ),
        migrations.AddIndex(
            model_name='modificationspecification',
            index=models.Index(fields=['drive_type'], name='cars_spec_drive_idx'),
        ),
        migrations.AddIndex(
            model_name='modificationspecification',
            index=models.Index(fields=['powertrain_type'], name='cars_spec_powertrain_type_idx'),
        ),
        migrations.AddIndex(
            model_name='modificationspecification',
            index=models.Index(fields=['fuel_type'], name='cars_spec_fuel_type_idx'),
        ),
        migrations.AddIndex(
            model_name='modificationspecification',
            index=models.Index(fields=['horse_power_hp'], name='cars_spec_hp_idx'),
        ),
        migrations.AddIndex(
            model_name='modificationspecification',
            index=models.Index(fields=['displacement_cc'], name='cars_spec_displacement_idx'),
        ),
        migrations.AddIndex(
            model_name='modificationspecification',
            index=models.Index(fields=['electric_range_km'], name='cars_spec_ev_range_idx'),
        ),
        migrations.AddIndex(
            model_name='modificationspecification',
            index=models.Index(fields=['battery_capacity_kwh'], name='cars_spec_battery_idx'),
        ),
        migrations.AddIndex(
            model_name='modificationspecification',
            index=models.Index(fields=['seats_count'], name='cars_spec_seats_idx'),
        ),
        migrations.AddIndex(
            model_name='modificationspecification',
            index=models.Index(fields=['max_speed_kmh'], name='cars_spec_speed_idx'),
        ),
        migrations.AddIndex(
            model_name='optiondefinition',
            index=models.Index(fields=['category', 'is_active'], name='cars_optdef_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='modificationoption',
            index=models.Index(fields=['modification'], name='cars_modoption_modif_idx'),
        ),
        migrations.AddIndex(
            model_name='modificationoption',
            index=models.Index(fields=['option_definition'], name='cars_modoption_optdef_idx'),
        ),
        migrations.AddIndex(
            model_name='modificationoption',
            index=models.Index(fields=['option_definition', 'value_bool'], name='cars_modoption_opt_val_idx'),
        ),
        migrations.AddConstraint(
            model_name='modificationoption',
            constraint=models.UniqueConstraint(
                fields=('modification', 'option_definition'), name='cars_modoption_modification_option_uniq'
            ),
        ),
    ]
