# Generated by Django 5.2.6 on 2026-03-20 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('image', models.ImageField(upload_to='cars/configuration_photos/', verbose_name='изображение')),
                (
                    'source_file_name',
                    models.CharField(blank=True, db_index=True, max_length=255, verbose_name='имя исходного файла'),
                ),
                (
                    'source_configuration_id',
                    models.CharField(blank=True, db_index=True, max_length=64, verbose_name='source configuration id'),
                ),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='alt текст')),
                ('is_main', models.BooleanField(default=True, verbose_name='главное фото')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок сортировки')),
                (
                    'configuration',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='photo',
                        to='cars.configuration',
                        verbose_name='конфигурация',
                    ),
                ),
            ],
            options={
                'verbose_name': 'фото конфигурации',
                'verbose_name_plural': 'фото конфигураций',
                'ordering': ('sort_order', 'id'),
                'indexes': [
                    models.Index(fields=['source_configuration_id'], name='cars_cfgphoto_src_cfg_idx'),
                    models.Index(fields=['is_main', 'sort_order'], name='cars_cfgphoto_main_sort_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='MarkLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('image', models.ImageField(upload_to='cars/mark_logos/', verbose_name='логотип')),
                (
                    'source_file_name',
                    models.CharField(blank=True, db_index=True, max_length=255, verbose_name='имя исходного файла'),
                ),
                (
                    'source_mark_id',
                    models.CharField(blank=True, db_index=True, max_length=64, verbose_name='source mark id'),
                ),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='alt текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                (
                    'mark',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='logo',
                        to='cars.mark',
                        verbose_name='марка',
                    ),
                ),
            ],
            options={
                'verbose_name': 'логотип марки',
                'verbose_name_plural': 'логотипы марок',
                'ordering': ('mark__name',),
                'indexes': [
                    models.Index(fields=['source_mark_id'], name='cars_marklogo_src_mark_idx'),
                    models.Index(fields=['is_active'], name='cars_marklogo_active_idx'),
                ],
            },
        ),
    ]
