# Generated by Django 5.2.6 on 2026-03-20 15:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_configurationphoto_marklogo'),
        ('catalog', '0001_initial'),
        ('main', '0002_set_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                (
                    'user_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('full_name', models.CharField(max_length=255, verbose_name='полное имя')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
            bases=('main.user',),
        ),
        migrations.CreateModel(
            name='ClientCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('license_plate', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='госномер')),
                (
                    'vin',
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='VIN'
                    ),
                ),
                (
                    'mileage_km',
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)], verbose_name='пробег, км'
                    ),
                ),
                ('year', models.PositiveSmallIntegerField(verbose_name='год выпуска')),
                ('is_primary', models.BooleanField(db_index=True, default=False, verbose_name='активный автомобиль')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активна')),
                (
                    'client',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cars',
                        to='client.client',
                        verbose_name='клиент',
                    ),
                ),
                (
                    'modification',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='client_cars',
                        to='cars.modification',
                        verbose_name='модификация',
                    ),
                ),
            ],
            options={
                'verbose_name': 'автомобиль клиента',
                'verbose_name_plural': 'автомобили клиентов',
                'ordering': ('-is_primary', '-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ClientPackageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                (
                    'status',
                    models.CharField(
                        choices=[('NEW', 'Новая'), ('CANCELLED', 'Отменена')],
                        db_index=True,
                        default='NEW',
                        max_length=20,
                        verbose_name='статус',
                    ),
                ),
                ('client_full_name_snapshot', models.CharField(max_length=255, verbose_name='имя клиента (snapshot)')),
                ('client_email_snapshot', models.EmailField(max_length=254, verbose_name='email клиента (snapshot)')),
                ('car_license_plate_snapshot', models.CharField(max_length=32, verbose_name='госномер (snapshot)')),
                ('car_vin_snapshot', models.CharField(blank=True, max_length=64, verbose_name='VIN (snapshot)')),
                ('car_year_snapshot', models.PositiveSmallIntegerField(verbose_name='год выпуска (snapshot)')),
                ('car_mileage_km_snapshot', models.PositiveIntegerField(verbose_name='пробег, км (snapshot)')),
                (
                    'car_modification_source_id_snapshot',
                    models.CharField(db_index=True, max_length=128, verbose_name='source_id модификации (snapshot)'),
                ),
                (
                    'car_modification_title_snapshot',
                    models.CharField(max_length=1000, verbose_name='название модификации (snapshot)'),
                ),
                (
                    'package_name_snapshot',
                    models.CharField(max_length=255, verbose_name='внутреннее название пакета (snapshot)'),
                ),
                (
                    'package_public_title_snapshot',
                    models.CharField(max_length=255, verbose_name='публичный заголовок пакета (snapshot)'),
                ),
                (
                    'package_category_name_snapshot',
                    models.CharField(max_length=255, verbose_name='категория пакета (snapshot)'),
                ),
                (
                    'package_slug_snapshot',
                    models.SlugField(allow_unicode=True, max_length=255, verbose_name='slug пакета (snapshot)'),
                ),
                (
                    'regular_price_snapshot',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='обычная цена (snapshot)'
                    ),
                ),
                (
                    'final_price_snapshot',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=12,
                        verbose_name='итоговая цена (snapshot)',
                    ),
                ),
                ('is_promo_snapshot', models.BooleanField(default=False, verbose_name='акция (snapshot)')),
                ('promo_text_snapshot', models.TextField(blank=True, verbose_name='текст акции (snapshot)')),
                (
                    'package_items_snapshot',
                    models.TextField(
                        blank=True,
                        help_text='JSON-строка со статичным составом пакета на момент покупки.',
                        verbose_name='состав пакета (snapshot)',
                    ),
                ),
                (
                    'client',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='package_orders',
                        to='client.client',
                        verbose_name='клиент',
                    ),
                ),
                (
                    'client_car',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='package_orders',
                        to='client.clientcar',
                        verbose_name='автомобиль клиента',
                    ),
                ),
                (
                    'package',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='client_orders',
                        to='catalog.carservicepackage',
                        verbose_name='пакет',
                    ),
                ),
            ],
            options={
                'verbose_name': 'покупка пакета клиентом',
                'verbose_name_plural': 'покупки пакетов клиентами',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='clientcar',
            index=models.Index(fields=['client', 'is_primary'], name='clients_car_client_primary_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcar',
            index=models.Index(fields=['client', 'is_active'], name='clients_car_client_active_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcar',
            index=models.Index(fields=['modification'], name='clients_car_modification_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcar',
            index=models.Index(fields=['year'], name='clients_car_year_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientcar',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_primary', True)),
                fields=('client',),
                name='clients_clientcar_one_primary_per_client_uniq',
            ),
        ),
        migrations.AddIndex(
            model_name='clientpackageorder',
            index=models.Index(fields=['client', 'status'], name='cl_ord_cli_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpackageorder',
            index=models.Index(fields=['client_car'], name='cl_ord_car_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpackageorder',
            index=models.Index(fields=['package'], name='cl_ord_pkg_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpackageorder',
            index=models.Index(fields=['status', 'created_at'], name='cl_ord_stat_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpackageorder',
            index=models.Index(fields=['car_modification_source_id_snapshot'], name='cl_ord_modsrc_idx'),
        ),
    ]
